# Generated by Django 5.0.7 on 2024-07-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название урока')),
                ('description', models.TextField(verbose_name='описание урока')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lesson/images', verbose_name='картинка (превью)')),
                ('link', models.URLField(blank=True, max_length=300, null=True, verbose_name='ссылка на видео')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название курса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='course/images', verbose_name='картинка (превью)')),
                ('description', models.TextField(verbose_name='описание курса')),
                ('lessons', models.ManyToManyField(related_name='related_lesson', to='materials.lesson')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
    ]
