# Generated by Django 5.0.7 on 2024-07-26 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lessons',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Выберите курс', null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.course', verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='Укажите описание курса', verbose_name='описание курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Добавьте превью изображения', null=True, upload_to='course/images', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='Укажите название курса', max_length=200, verbose_name='название курса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(help_text='Укажите описание урока', verbose_name='описание урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, help_text='Добавьте превью изображения', null=True, upload_to='lesson/images', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='link',
            field=models.URLField(blank=True, help_text='Укажите ссылку', max_length=300, null=True, verbose_name='ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(help_text='Укажите название урок', max_length=200, verbose_name='название урока'),
        ),
    ]
