# Generated by Django 5.0.7 on 2024-07-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_remove_course_lessons_lesson_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_lesson', to='materials.lesson'),
        ),
    ]
