# Generated by Django 5.0.7 on 2024-07-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_remove_lesson_course_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_course', to='materials.course'),
        ),
    ]
