# Generated by Django 5.0.7 on 2024-08-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_remove_lesson_course_lesson_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': [('can_view_course', 'Может просматривать курсы'), ('can_edit_course', 'Может редактировать курсы')], 'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'permissions': [('can_view_lesson', 'Может просматривать уроки'), ('can_edit_lesson', 'Может редактировать уроки')], 'verbose_name': 'урок', 'verbose_name_plural': 'уроки'},
        ),
    ]
