# Generated by Django 5.0.7 on 2024-08-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.URLField(blank=True, help_text='Укажите ссылку', max_length=300, null=True, verbose_name='ссылка на видео'),
        ),
    ]
