# Generated by Django 5.0.7 on 2024-08-16 09:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Последнее обновление'),
            preserve_default=False,
        ),
    ]
